# helm/my-flask-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-flask-app.fullname" . }}
  labels:
    {{- include "my-flask-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-flask-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-flask-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: AWS_REGION
              value: {{ .Values.env.AWS_REGION }}
            - name: DYNAMODB_TABLE
              value: {{ .Values.env.DYNAMODB_TABLE }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
