name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to destroy'
        required: true
        type: choice
        options:
          - feature
          - dev
      destroy_backend:
        description: 'Destroy the S3 backend and DynamoDB lock table? (very destructive!)'
        required: true
        type: boolean
        default: false

jobs:
  destroy-environment:
    name: "Destroy ${{ github.event.inputs.environment }} environment"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=my-flask-app-terraform-state" \
            -backend-config="key=${{ github.event.inputs.environment }}/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=my-flask-app-terraform-lock"
        working-directory: terraform/environments/${{ github.event.inputs.environment }}

      - name: Terraform Destroy
        run: terraform destroy -var-file="${{ github.event.inputs.environment }}.tfvars" -auto-approve
        working-directory: terraform/environments/${{ github.event.inputs.environment }}

  destroy-backend:
    name: "Destroy S3 Backend"
    runs-on: ubuntu-latest
    needs: destroy-environment
    if: github.event.inputs.destroy_backend == true
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Destroy Backend Resources with AWS CLI
        run: |
          set -e
          PROJECT_NAME="my-flask-app"
          S3_BUCKET_NAME="${PROJECT_NAME}-terraform-state"
          DYNAMODB_TABLE_NAME="${PROJECT_NAME}-terraform-lock"

          echo "Attempting to delete S3 bucket: $S3_BUCKET_NAME"
          aws s3 rb "s3://$S3_BUCKET_NAME" --force || echo "S3 bucket $S3_BUCKET_NAME did not exist or could not be deleted."

          echo "Attempting to delete DynamoDB table: $DYNAMODB_TABLE_NAME"
          aws dynamodb delete-table --table-name "$DYNAMODB_TABLE_NAME" || echo "DynamoDB table $DYNAMODB_TABLE_NAME did not exist or could not be deleted."
