# .github/workflows/destroy.yml
name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION || 'ap-south-1' }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=feature/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION || 'ap-south-1' }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_STATE_LOCK_TABLE }}"
        working-directory: terraform/environments/feature

      - name: Terraform Destroy
        run: terraform destroy -var-file="feature.tfvars" -auto-approve
        working-directory: terraform/environments/feature
