name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      tf_state_bucket:
        description: 'S3 bucket for Terraform state'
        required: true
      tf_state_lock_table:
        description: 'DynamoDB table for Terraform state lock'
        required: true

jobs:
  destroy-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ github.event.inputs.tf_state_bucket }}" \
            -backend-config="key=feature/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ github.event.inputs.tf_state_lock_table }}"
        working-directory: terraform/environments/feature

      - name: Terraform Destroy
        run: terraform destroy -var-file="feature.tfvars" -auto-approve
        working-directory: terraform/environments/feature
