name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  backend-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'ap-south-1' }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: terraform/backend_setup

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -var="bucket_name=${{ secrets.TF_STATE_BUCKET }}" -var="table_name=${{ secrets.TF_STATE_LOCK_TABLE }}"
        working-directory: terraform/backend_setup

  build-and-deploy:
    needs: backend-setup
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION || 'ap-south-1' }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover tests

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=feature/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION || 'ap-south-1' }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_STATE_LOCK_TABLE }}"
        working-directory: terraform/environments/feature

      - name: Terraform Apply
        run: terraform apply -var-file="feature.tfvars" -auto-approve
        working-directory: terraform/environments/feature

      - name: Get ECR Repository URL
        id: ecr-url
        run: |
          ecr_repo_url=$(terraform output -raw ecr_repository_url)
          echo "ecr_repo_url=$ecr_repo_url" >> $GITHUB_OUTPUT
        working-directory: terraform/environments/feature

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REPOSITORY_URL: ${{ steps.ecr-url.outputs.ecr_repo_url }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REPOSITORY_URL:$IMAGE_TAG .
          docker push $ECR_REPOSITORY_URL:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REPOSITORY_URL:$IMAGE_TAG"

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.build-image.outputs.image }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER }} --region ${{ secrets.AWS_REGION || 'ap-south-1' }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install my-flask-app ./helm/my-flask-app \
            --set image.repository=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }} \
            --set image.tag=${{ github.sha }} \
            --namespace default \
            --create-namespace
